In [3]:
#task: 1.1
nums = [3, 5, 7, 8, 12]

cubes = []

for num in nums:
    cubes.append(num ** 3)

print("Cubes:", cubes)


Cubes: [27, 125, 343, 512, 1728]


In [5]:
#task: 1.2
dict = {}

dict['parrot'] = 2
dict['goat'] = 4
dict['spider'] = 8
dict['crab'] = 10

print(dict)


{'parrot': 2, 'goat': 4, 'spider': 8, 'crab': 10}


In [3]:
#task: 1.3

dict = {}

dict['parrot'] = 2
dict['goat'] = 4
dict['spider'] = 8
dict['crab'] = 10

total_legs = 0

for animal, dict in dict.items():
    print(f"The {animal} has {dict} legs.")
    total_legs += dict 

print(f"\nTotal number of legs: {total_legs}")

The parrot has 2 legs.
The goat has 4 legs.
The spider has 8 legs.
The crab has 10 legs.

Total number of legs: 24


In [5]:
#task: 1.4

A = (3, 9, 4, [5, 6])

A[3][0] = 8

print(A)


(3, 9, 4, [8, 6])


In [11]:
#task: 1.5

A = (3, 9, 4, [5, 6])

A[3][0] = 8

print(A)

del A

try:
    print(A)
except NameError as e:
    print(e)


(3, 9, 4, [8, 6])
name 'A' is not defined


In [13]:
#task: 1.6

B = ('a', 'p', 'p', 'l', 'e')
count_p = B.count('p')
print(count_p)



2


In [15]:
#task; 1.7

B = ('a', 'p', 'p', 'l', 'e')
index_l = B.index('l')
print(index_l)


3


In [17]:
#Task: 2 Numpy
#task: 2.1

import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print(A)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
#Task: 2.2

import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

b = A[:2, 1:3]

print(b)



[[2 3]
 [6 7]]


In [21]:
#Task: 2.3 

import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

C = np.empty_like(A)

print(C)


[[1819305298  543515489 1835365481 1702043763]
 [1952671084 1998611557  543716457 1634541665]
 [     27507 1970037110      29541          0]]


In [23]:
#Task: 2.4

import numpy as np
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

z = np.array([1, 0, 1])

C = np.empty_like(A)

for i in range(A.shape[1]):  # Iterate over columns
    C[:, i] = A[:, i] + z

print(C)


[[ 2  3  4  5]
 [ 5  6  7  8]
 [10 11 12 13]]


In [1]:
#Task: 2.5
import numpy as np

X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])

Z = X + Y

print(Z)


[[ 6  8]
 [10 12]]


In [3]:
#Task: 2.6
import numpy as np

X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])

Z = np.dot(X, Y) 

print(Z)


[[19 22]
 [43 50]]


In [5]:
#Task: 2.7
import numpy as np

Y = np.array([[5, 6], [7, 8]])

sqrt_Y = np.sqrt(Y)

print(sqrt_Y)


[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [7]:
#Task: 2.8
import numpy as np

X = np.array([[1, 2], [3, 4]])
v = np.array([9, 10])

dot_product = np.dot(X, v) 

print(dot_product)


[29 67]


In [9]:
#Task: 2.9
import numpy as np

X = np.array([[1, 2], [3, 4]])

column_sum = np.sum(X, axis=0)

print(column_sum)


[4 6]


In [13]:
#Task 3: Functions and Loops
#Task:3.1
def Compute(distance, time):
    
    if time == 0:
        return "Time cannot be zero"
    velocity = distance / time
    return velocity

distance = 100  
time = 10      
print("Velocity:", Compute(distance, time), "m/s")


Velocity: 10.0 m/s


In [15]:
#Task: 3.2

even_num = [2, 4, 6, 8, 10, 12]

def mult(numbers):
    product = 1
    for num in numbers:
        product *= num
    return product

result = mult(even_num)
print(result)


46080


In [17]:
#Task 4: Pandas
#Task: 4.1
import pandas as pd

data = {'C1': [1, 2, 3, 5, 5],
        'C2': [6, 7, 5, 4, 8],
        'C3': [7, 9, 8, 6, 5],
        'C4': [7, 5, 2, 8, 8]}

df = pd.DataFrame(data)
print(df.head(2))


   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5


In [19]:
#Task: 4.2
import pandas as pd

data = {'C1': [1, 2, 3, 5, 5],
        'C2': [6, 7, 5, 4, 8],
        'C3': [7, 9, 8, 6, 5],
        'C4': [7, 5, 2, 8, 8]}

df = pd.DataFrame(data)

print(df['C2'])


0    6
1    7
2    5
3    4
4    8
Name: C2, dtype: int64


In [21]:
#Task: 4.3
import pandas as pd

data = {'C1': [1, 2, 3, 5, 5],
        'C2': [6, 7, 5, 4, 8],
        'C3': [7, 9, 8, 6, 5],
        'C4': [7, 5, 2, 8, 8]}

df = pd.DataFrame(data)

df.rename(columns={'C3': 'B3'}, inplace=True)

print(df)


   C1  C2  B3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [23]:
#Task: 4.4
import pandas as pd

data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

df = pd.DataFrame(data)

df['Sum'] = df.sum(axis=1)

print(df)


   C1  C2  C3  C4  Sum
0   1   6   7   7   21
1   2   7   9   5   23
2   3   5   8   2   18
3   5   4   6   8   23
4   5   8   5   8   26


In [25]:
#Task: 4.5
import pandas as pd
data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

df = pd.DataFrame(data)

df['Sum'] = df.sum(axis=1)

print(df)


   C1  C2  C3  C4  Sum
0   1   6   7   7   21
1   2   7   9   5   23
2   3   5   8   2   18
3   5   4   6   8   23
4   5   8   5   8   26


In [ ]:
#Task: 4.6
import pandas as pd

file_path = 'hello_sample.csv' 

df = pd.read_csv(file_path)
print(df)

In [29]:
#Task: 4.7
import pandas as pd

pd.set_option('display.max_rows', None)  
pd.set_option('display.max_columns', None) 

print(df)

   C1  C2  C3  C4  Sum
0   1   6   7   7   21
1   2   7   9   5   23
2   3   5   8   2   18
3   5   4   6   8   23
4   5   8   5   8   26


In [3]:
#Task: 4.8
import pandas as pd
data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

df = pd.DataFrame(data)

print(df.tail(2))



   C1  C2  C3  C4
3   5   4   6   8
4   5   8   5   8


In [5]:
#Task: 4.9
import pandas as pd
data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

df = pd.DataFrame(data)

print(df.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C1      5 non-null      int64
 1   C2      5 non-null      int64
 2   C3      5 non-null      int64
 3   C4      5 non-null      int64
dtypes: int64(4)
memory usage: 292.0 bytes
None


In [7]:
#Task: 4.10
import pandas as pd

data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

df = pd.DataFrame(data)

print(df.shape)



(5, 4)


In [37]:
#Task: 4.11
import pandas as pd

data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

df = pd.DataFrame(data)

df_sorted = df.sort_values(by='C2')

print(df_sorted)


   C1  C2  C3  C4
3   5   4   6   8
2   3   5   8   2
0   1   6   7   7
1   2   7   9   5
4   5   8   5   8


In [39]:
#Task: 4.12
import pandas as pd
import numpy as np

data = {
    'C1': [1, 2, np.nan, 5, 5],  
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, np.nan, 5], 
    'C4': [7, 5, 2, 8, 8],
    'Weight': [10, 20, 15, 5, np.nan] 
}

df = pd.DataFrame(data)

print("Missing values in the DataFrame:")
print(df.isnull())

df_cleaned = df.dropna()

print("\nDataFrame after dropping rows with missing values:")
print(df_cleaned)


Missing values in the DataFrame:
      C1     C2     C3     C4  Weight
0  False  False  False  False   False
1  False  False  False  False   False
2   True  False  False  False   False
3  False  False   True  False   False
4  False  False  False  False    True

DataFrame after dropping rows with missing values:
    C1  C2   C3  C4  Weight
0  1.0   6  7.0   7    10.0
1  2.0   7  9.0   5    20.0
